services:
  server:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: rankhub-api
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
    ports:
      - 3001:3001
    volumes:
      - ./apps/api:/usr/src/apps/api # for dev hot-reload (remove in prod)
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    container_name: rankhub-db
    volumes:
      - rankhub_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_HOST}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: rankhub-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  rankhub_pg:
